meta_type: 'implicit'
use_gpu: true
save_dir: ""
seed: 2022
net: 'ncsnv2'

data:
 dataset: 'celeba'
 train_batch_size: 16
 val_batch_size: 16
 num_channels: 3
 num_train: 32
 num_val: 32
 num_test: 64

outer:
 hyperparam_type: 'scalar'
 num_epochs: 20
 optimizer: 'adam'
 lr: 0.1
 lr_decay: 0.95
 verbose: true
 debug: false
 checkpoint_epochs: 4
 cg_iters: 25
 cg_verbose: 5
 cg_tol: 0.0000000001
 cg_damping: 0.1
 finite_difference: false
 finite_difference_coeff: 0.00000001
 measurement_loss: false
 train_loss_type: 'l2'
 ROI: false

inner:
 alg: 'map'
 T: 5
 decimation_factor: 5
 decimation_type: 'linear'
 verbose: 100
 lr: 0.0000033

problem:
 measurement_type: 'gaussian'
 num_measurements: 1000
 downsample_factor: 2
 inpaint_size: 20
 add_noise: false
 noise_type: "gaussian"
 noise_std: 1
 add_dependent_noise: false
 dependent_noise_type: "gaussian"
 dependent_noise_std: 1
